server:
  port: 8888
spring:
  profiles:
    active: prod
  banner:
    location: banner.txt
  main:
    banner-mode: console
  thymeleaf:
    cache: false
  mvc:
    favicon:
      enabled: false

comment.avatar: /images/fine-1.gif

mybatis:
  #扫描Entity, 加入此设置方可在Mybatis的XML文件中使用实体类的Alias
  typeAliasesPackage: com.lyq.blog.model
  #扫描Mybatis的XML文件,
  mapperLocations: com/lyq/blog/mapper/*.xml
  configuration:
    #开启驼峰映射
    map-underscore-to-camel-case: true
    #日志实现
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl