spring:
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  profiles:
    active: dev
  resources:
    static-locations: classpath:/templates/

logging:
  config: src/main/resources/config/ logback-spring.xml