spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.107.229.6:3306/myblog?useUnicode=true&characterEncoding=utf-8 # &serverTimezone=Asia/Shanghai
    username: windows
    password: 8880
  thymeleaf:
    cache: false
  jpa:
    open-in-view: true

comment.avatar: /images/fine-1.gif
server:
  port: 8888