server:
  port: 8888
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.3.183.202:3306/myblog?useUnicode=true&characterEncoding=utf-8 # &serverTimezone=Asia/Shanghai
    username: linux
    password: 8880
  thymeleaf:
    cache: false
  jpa:
    open-in-view: true
  mvc:
    favicon:
      enabled: false
comment.avatar: /images/fine-1.gif
